version: '3.9'
services:
  app:
    image: maven:3.8.3-openjdk-17
    volumes:
      - ./warehouse:/warehouse
    container_name: myapp-container
    ports:
      - 9096:9096
    working_dir: /warehouse
    command: mvn spring-boot:run
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mysql
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql123
    depends_on:
      - db
    
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=mysql123
      - MYSQL_DATABASE=mysql
    ports:
      - 3306:3306


